exp_name: 'pockets_full_no_anchors_fc'
data: /home/igashov/work/diffusion_linker_data/e3_ddpm_linker_design/bindingmoad
train_data_prefix: MOAD_train.full
val_data_prefix: MOAD_val.full
checkpoints: /home/igashov/work/diffusion_linker_data/e3_ddpm_linker_design/checkpoints
logs: /home/igashov/work/diffusion_linker_data/e3_ddpm_linker_design/logs
device: gpu
log_iterations: null
wandb_entity: geometric
enable_progress_bar: False

model: egnn_dynamics
lr: 2.0e-4
batch_size: 16
n_layers: 6
n_epochs: 1000
test_epochs: 20
n_stability_samples: 5
nf: 128
activation: silu
attention: False
condition_time: True
tanh: False
norm_constant: 0.000001
inv_sublayers: 2
include_charges: False
diffusion_loss_type: l2
data_augmentation: False
center_of_mass: fragments
remove_anchors_context: True
graph_type: FC-10A-4A

sin_embedding: False
normalization_factor: 100
normalize_factors: [1, 4, 10]
aggregation_method: 'sum'
normalization: batch_norm

resume:
